export enum KycSessionStatus {
  AWAITING_DOCUMENT = 'AWAITING_DOCUMENT',
  DOCUMENT_PROCESSING = 'DOCUMENT_PROCESSING',
  DOCUMENT_PROCESSING_FAILED = 'DOCUMENT_PROCESSING_FAILED',
  DOCUMENT_REQUIRES_RETAKE = 'DOCUMENT_REQUIRES_RETAKE',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_OCR_COMPLETED = 'DOCUMENT_OCR_COMPLETED',
}
